POST http://localhost:3333/api/links
 Content-Type: application/json

 {
  "code" : "portifolio",
  "url" : "https://my-portfolio-nine-roan-23.vercel.app"
 }

###

GET http://localhost:3333/api/links

###
GET http://localhost:3333/portifolio
